"""initial_soc_schema

Revision ID: 3a467a50c963
Revises: 
Create Date: 2026-09-29 16:46:07.025619+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a467a50c963'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_hash'), ['hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_log_ts'), ['ts'], unique=False)

    op.create_table('counters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counters', schema=None) as batch_op:
        batch_op.create_index('idx_counters_bucket_label', ['ts_bucket', 'label'], unique=True)
        batch_op.create_index(batch_op.f('ix_counters_label'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('ix_counters_ts_bucket'), ['ts_bucket'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key_src_ip', sa.String(length=45), nullable=False),
    sa.Column('family', sa.String(length=50), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('max_risk', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CONTAINED', 'CLOSED', 'FALSE_POSITIVE', name='incident_status_enum'), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('idx_incidents_src_family', ['key_src_ip', 'family'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_family'), ['family'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_key_src_ip'), ['key_src_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=False),
    sa.Column('dst_ip', sa.String(length=45), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('family', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=False),
    sa.Column('probabilities', sa.JSON(), nullable=False),
    sa.Column('top_features', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('raw_features', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('idx_alerts_src_ts', ['src_ip', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_family'), ['family'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_label'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_src_ip'), ['src_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_ts'), ['ts'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('rule_trace', sa.JSON(), nullable=False),
    sa.Column('policy_hash', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.Enum('MONITOR', 'RECOMMEND', 'AUTO', name='decision_mode_enum'), nullable=False),
    sa.Column('playbook_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('MONITORED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTED', 'FAILED', 'EXPIRED', name='decision_status_enum'), nullable=False),
    sa.Column('guardrail_results', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_tier'), ['tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_ts'), ['ts'], unique=False)

    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('executor', sa.String(length=50), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_status'), ['status'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('analyst', sa.String(length=100), nullable=False),
    sa.Column('verdict', sa.Enum('APPROVE', 'REJECT', 'OVERRIDE', name='approval_verdict_enum'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_ts'), ['ts'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('analyst', sa.String(length=100), nullable=False),
    sa.Column('true_label', sa.String(length=100), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_ts'), ['ts'], unique=False)

    op.create_table('virtual_firewall',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.Enum('BLOCK', 'ISOLATE', 'RATE_LIMIT', name='vf_kind_enum'), nullable=False),
    sa.Column('target', sa.String(length=45), nullable=False),
    sa.Column('ttl_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('virtual_firewall', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_virtual_firewall_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_virtual_firewall_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_virtual_firewall_target'), ['target'], unique=False)
        batch_op.create_index(batch_op.f('ix_virtual_firewall_ttl_at'), ['ttl_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_firewall', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_virtual_firewall_ttl_at'))
        batch_op.drop_index(batch_op.f('ix_virtual_firewall_target'))
        batch_op.drop_index(batch_op.f('ix_virtual_firewall_kind'))
        batch_op.drop_index(batch_op.f('ix_virtual_firewall_active'))

    op.drop_table('virtual_firewall')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_ts'))
        batch_op.drop_index(batch_op.f('ix_feedback_alert_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_ts'))
        batch_op.drop_index(batch_op.f('ix_approvals_decision_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_status'))
        batch_op.drop_index(batch_op.f('ix_actions_expires_at'))
        batch_op.drop_index(batch_op.f('ix_actions_decision_id'))

    op.drop_table('actions')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_ts'))
        batch_op.drop_index(batch_op.f('ix_decisions_tier'))
        batch_op.drop_index(batch_op.f('ix_decisions_status'))
        batch_op.drop_index(batch_op.f('ix_decisions_rule_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_mode'))
        batch_op.drop_index(batch_op.f('ix_decisions_incident_id'))

    op.drop_table('decisions')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_status'))
        batch_op.drop_index(batch_op.f('ix_cases_incident_id'))
        batch_op.drop_index(batch_op.f('ix_cases_created_at'))

    op.drop_table('cases')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_ts'))
        batch_op.drop_index(batch_op.f('ix_alerts_src_ip'))
        batch_op.drop_index(batch_op.f('ix_alerts_label'))
        batch_op.drop_index(batch_op.f('ix_alerts_incident_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_family'))
        batch_op.drop_index('idx_alerts_src_ts')

    op.drop_table('alerts')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_last_seen'))
        batch_op.drop_index(batch_op.f('ix_incidents_key_src_ip'))
        batch_op.drop_index(batch_op.f('ix_incidents_family'))
        batch_op.drop_index('idx_incidents_src_family')

    op.drop_table('incidents')
    with op.batch_alter_table('counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counters_ts_bucket'))
        batch_op.drop_index(batch_op.f('ix_counters_label'))
        batch_op.drop_index('idx_counters_bucket_label')

    op.drop_table('counters')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_log_hash'))
        batch_op.drop_index(batch_op.f('ix_audit_log_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
